# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Location Not Provided', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Description Default Text'),
        ),
    ]
