# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180916_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.AddField(
            model_name='profile',
            name='Description',
            field=models.TextField(default='Description Not Provided'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Job',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
