# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180916_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Location',
            field=models.CharField(blank=True, default='Location Not Provided', max_length=120, null=True),
        ),
    ]
