# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20180916_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Job',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Location',
        ),
    ]
